import base64
import binascii
import math
from collections import Counter
from typing import Any, cast

from pydantic import SecretStr, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

MIN_AUTH_SESSION_HMAC_SECRET_BYTES = 32
MIN_ENCRYPTION_KEY_BYTES = 32
MIN_ENCRYPTION_KEY_UNIQUE_BYTES = 12
MIN_ENCRYPTION_KEY_ENTROPY_BITS_PER_BYTE = 3.0
SMTP_DENY_ALL_HOST_MARKER = "__deny_all__"
SMTP_ALLOWED_EGRESS_PORTS = frozenset({25, 465, 587})
DEFAULT_ALLOWED_BROWSER_ORIGINS = (
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
)
_LOW_ENTROPY_PLACEHOLDER_TERMS = ("change", "example", "password", "secret")
_KNOWN_PUBLIC_AUTH_SESSION_HMAC_SECRETS = frozenset(
    {"naruon-session-hmac-token-32-byte-minimum"}
)
_KNOWN_WEAK_ENCRYPTION_KEYS = frozenset(
    {
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
    }
)


def validate_auth_session_hmac_secret_value(secret: str) -> None:
    secret_bytes = secret.encode("utf-8")
    if len(secret_bytes) < MIN_AUTH_SESSION_HMAC_SECRET_BYTES:
        raise ValueError(
            "AUTH_SESSION_HMAC_SECRET must be at least 32 bytes in all environments"
        )
    if len(set(secret)) == 1:
        raise ValueError("AUTH_SESSION_HMAC_SECRET must not be a repeated character")
    normalized_secret = secret.lower()
    if normalized_secret in _KNOWN_PUBLIC_AUTH_SESSION_HMAC_SECRETS:
        raise ValueError("AUTH_SESSION_HMAC_SECRET must not use a public fixture value")
    if any(term in normalized_secret for term in _LOW_ENTROPY_PLACEHOLDER_TERMS):
        raise ValueError("AUTH_SESSION_HMAC_SECRET must not contain placeholder terms")


def _decoded_key_entropy_bits_per_byte(key_bytes: bytes) -> float:
    counts = Counter(key_bytes)
    total = len(key_bytes)
    return -sum((count / total) * math.log2(count / total) for count in counts.values())


def validate_encryption_key_value(secret: str) -> None:
    if secret != secret.strip() or not secret:
        raise ValueError(
            "ENCRYPTION_KEY must be a valid Fernet key without surrounding whitespace"
        )

    try:
        decoded_key = base64.b64decode(
            secret.encode("ascii"), altchars=b"-_", validate=True
        )
    except (UnicodeEncodeError, ValueError, binascii.Error) as exc:
        raise ValueError(
            "ENCRYPTION_KEY must be a valid Fernet key generated by Fernet.generate_key()"
        ) from exc

    if len(decoded_key) != MIN_ENCRYPTION_KEY_BYTES:
        raise ValueError(
            "ENCRYPTION_KEY must decode to a 32-byte Fernet key generated by Fernet.generate_key()"
        )

    if secret in _KNOWN_WEAK_ENCRYPTION_KEYS:
        raise ValueError("ENCRYPTION_KEY must not use a known weak Fernet key")

    if len(set(decoded_key)) < MIN_ENCRYPTION_KEY_UNIQUE_BYTES:
        raise ValueError(
            "ENCRYPTION_KEY must be generated from a high-entropy random source"
        )

    if (
        _decoded_key_entropy_bits_per_byte(decoded_key)
        < MIN_ENCRYPTION_KEY_ENTROPY_BITS_PER_BYTE
    ):
        raise ValueError(
            "ENCRYPTION_KEY must be generated from a high-entropy random source"
        )


def _csv_policy_values(value: str) -> tuple[str, ...]:
    return tuple(item.strip().lower() for item in value.split(",") if item.strip())


def validate_allowed_smtp_hosts_value(value: str) -> None:
    host_values = _csv_policy_values(value)
    if not host_values:
        raise ValueError(
            "ALLOWED_SMTP_HOSTS must use the deny-all marker or explicit relay hosts"
        )

    if SMTP_DENY_ALL_HOST_MARKER in host_values:
        if host_values != (SMTP_DENY_ALL_HOST_MARKER,):
            raise ValueError(
                "ALLOWED_SMTP_HOSTS deny-all marker cannot be mixed with relay hosts"
            )
        return

    for host_value in host_values:
        if (
            "*" in host_value
            or "://" in host_value
            or any(character in host_value for character in " \t\r\n/")
            or host_value in {"localhost", "localhost.localdomain"}
        ):
            raise ValueError(
                "ALLOWED_SMTP_HOSTS must contain only explicit relay hostnames or public IPs"
            )


def validate_allowed_smtp_ports_value(value: str) -> None:
    port_values = _csv_policy_values(value)
    if not port_values:
        raise ValueError("ALLOWED_SMTP_PORTS must explicitly list allowed SMTP ports")
    for port_value in port_values:
        try:
            port_number = int(port_value)
        except ValueError as exc:
            raise ValueError("ALLOWED_SMTP_PORTS entries must be integers") from exc
        if port_number not in SMTP_ALLOWED_EGRESS_PORTS:
            raise ValueError("ALLOWED_SMTP_PORTS may only contain 25, 465, or 587")


def allowed_browser_origins(value: str | None = None) -> tuple[str, ...]:
    configured = ",".join(DEFAULT_ALLOWED_BROWSER_ORIGINS) if value is None else value
    origins = tuple(
        origin.strip().rstrip("/") for origin in configured.split(",") if origin.strip()
    )
    return origins or DEFAULT_ALLOWED_BROWSER_ORIGINS


class Settings(BaseSettings):
    DATABASE_URL: str
    DEBUG: bool = False
    RUNTIME_ENVIRONMENT: str = "production"
    AUTH_SESSION_HMAC_SECRET: SecretStr | None = None
    ENCRYPTION_KEY: SecretStr | None = None
    CONTROL_PLANE_DOMAIN: str = "naruon.net"
    ALLOWED_BROWSER_ORIGINS: str = ",".join(DEFAULT_ALLOWED_BROWSER_ORIGINS)
    ALLOWED_SMTP_HOSTS: str = SMTP_DENY_ALL_HOST_MARKER
    ALLOWED_SMTP_PORTS: str = "465,587"
    ALLOWED_LLM_BASE_URL_HOSTS: str = ""

    # OpenAI Settings
    OPENAI_EMBEDDING_MODEL: str = "text-embedding-3-small"
    OPENAI_MODEL: str = "gpt-4o"

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8")

    @model_validator(mode="after")
    def validate_session_secret(self) -> "Settings":
        configured = self.AUTH_SESSION_HMAC_SECRET
        if configured is None:
            raise ValueError(
                "AUTH_SESSION_HMAC_SECRET is required in all runtime environments"
            )

        validate_auth_session_hmac_secret_value(configured.get_secret_value())
        return self

    @model_validator(mode="after")
    def validate_encryption_key(self) -> "Settings":
        configured = self.ENCRYPTION_KEY
        if configured is not None:
            validate_encryption_key_value(configured.get_secret_value())
        return self

    @model_validator(mode="after")
    def validate_smtp_egress_policy(self) -> "Settings":
        validate_allowed_smtp_hosts_value(self.ALLOWED_SMTP_HOSTS)
        validate_allowed_smtp_ports_value(self.ALLOWED_SMTP_PORTS)
        return self


settings = Settings(**cast(dict[str, Any], {}))  # type: ignore
