from dataclasses import dataclass
import re

from cryptography.fernet import Fernet


MIN_AUTH_SESSION_HMAC_SECRET_BYTES = 32
_LOW_ENTROPY_PLACEHOLDER_TERMS = ("change", "example", "password", "secret")
_KNOWN_PUBLIC_AUTH_SESSION_HMAC_SECRETS = frozenset(
    {"naruon-session-hmac-token-32-byte-minimum"}
)
DEFAULT_ENCRYPTION_KEY_ID = "primary"
ENCRYPTION_KEY_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$")


@dataclass(frozen=True)
class RuntimeEncryptionKey:
    key_id: str
    fernet: Fernet


@dataclass(frozen=True)
class EncryptionKeyRing:
    active_key: RuntimeEncryptionKey
    previous_keys: tuple[RuntimeEncryptionKey, ...]

    def all_keys(self) -> tuple[RuntimeEncryptionKey, ...]:
        return (self.active_key, *self.previous_keys)

    def key_for_id(self, key_id: str) -> RuntimeEncryptionKey | None:
        for encryption_key in self.all_keys():
            if encryption_key.key_id == key_id:
                return encryption_key
        return None


import math

def _calculate_entropy(secret: str) -> float:
    if not secret:
        return 0.0
    char_counts = {}
    for char in secret:
        char_counts[char] = char_counts.get(char, 0) + 1
    entropy = 0.0
    length = len(secret)
    for count in char_counts.values():
        probability = count / length
        entropy -= probability * math.log2(probability)
    return entropy


def validate_auth_session_hmac_secret_value(secret: str) -> None:
    secret_bytes = secret.encode("utf-8")
    if len(secret_bytes) < MIN_AUTH_SESSION_HMAC_SECRET_BYTES:
        raise ValueError(
            "AUTH_SESSION_HMAC_SECRET must be at least 32 bytes in all environments"
        )
    if len(set(secret)) == 1:
        raise ValueError("AUTH_SESSION_HMAC_SECRET must not be a repeated character")

    entropy = _calculate_entropy(secret)
    if entropy < 3.0:
        raise ValueError("AUTH_SESSION_HMAC_SECRET lacks sufficient entropy. Please use a cryptographically secure random string.")

    normalized_secret = secret.lower()
    if normalized_secret in _KNOWN_PUBLIC_AUTH_SESSION_HMAC_SECRETS:
        raise ValueError("AUTH_SESSION_HMAC_SECRET must not use a public fixture value")
    if any(term in normalized_secret for term in _LOW_ENTROPY_PLACEHOLDER_TERMS):
        raise ValueError("AUTH_SESSION_HMAC_SECRET must not contain placeholder terms")


def validate_encryption_key_id(setting_name: str, key_id: str) -> str:
    normalized_key_id = key_id.strip()
    if not ENCRYPTION_KEY_ID_PATTERN.fullmatch(normalized_key_id):
        raise RuntimeError(
            f"{setting_name} must be 1-64 characters of letters, numbers, dot, "
            "underscore, or hyphen, and must start with a letter or number."
        )
    return normalized_key_id


def build_runtime_encryption_key(
    setting_name: str, key_id: str, key_value: str
) -> RuntimeEncryptionKey:
    normalized_key_id = validate_encryption_key_id(f"{setting_name} key id", key_id)
    normalized_key_value = key_value.strip()
    try:
        return RuntimeEncryptionKey(
            key_id=normalized_key_id,
            fernet=Fernet(normalized_key_value.encode("utf-8")),
        )
    except ValueError as exc:
        raise RuntimeError(
            f"{setting_name} must be a valid Fernet key generated by "
            "Fernet.generate_key()."
        ) from exc


def _parse_previous_encryption_keys(
    previous_keys_value: str | None,
) -> tuple[tuple[str, str], ...]:
    if previous_keys_value is None or not previous_keys_value.strip():
        return ()

    parsed_keys: list[tuple[str, str]] = []
    for raw_entry in previous_keys_value.split(","):
        entry = raw_entry.strip()
        if not entry:
            continue
        key_id, separator, key_value = entry.partition("=")
        if not separator or not key_id.strip() or not key_value.strip():
            raise RuntimeError(
                "ENCRYPTION_PREVIOUS_KEYS entries must use key_id=fernet_key"
            )
        parsed_keys.append((key_id.strip(), key_value.strip()))
    return tuple(parsed_keys)


def build_encryption_keyring(
    active_key_value: str | None,
    active_key_id: str = DEFAULT_ENCRYPTION_KEY_ID,
    previous_keys_value: str | None = None,
) -> EncryptionKeyRing:
    if active_key_value is None or not active_key_value.strip():
        raise RuntimeError(
            "ENCRYPTION_KEY is required. Refusing to encrypt without a configured key."
        )

    active_key = build_runtime_encryption_key(
        "ENCRYPTION_KEY",
        active_key_id or DEFAULT_ENCRYPTION_KEY_ID,
        active_key_value,
    )
    previous_keys: list[RuntimeEncryptionKey] = []
    configured_key_ids = {active_key.key_id}
    for previous_key_id, previous_key_value in _parse_previous_encryption_keys(
        previous_keys_value
    ):
        previous_key = build_runtime_encryption_key(
            "ENCRYPTION_PREVIOUS_KEYS",
            previous_key_id,
            previous_key_value,
        )
        if previous_key.key_id in configured_key_ids:
            raise RuntimeError(
                "ENCRYPTION_PREVIOUS_KEYS must not repeat key identifiers"
            )
        configured_key_ids.add(previous_key.key_id)
        previous_keys.append(previous_key)

    return EncryptionKeyRing(active_key=active_key, previous_keys=tuple(previous_keys))
