apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/seongho-bae/ai_email_client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://postgres:postgres@postgres-db:5432/ai_email"
        - name: AUTH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: ai-email-client-secrets
              key: auth-token-secret
